Facebook:
  Name: Facebook
  Description: Facebook is a social media platform that connects people with friends and others who work, study and live around them.

Twitter:
  Name: Twitter
  Description: Twitter is a social media platform that connects people with friends and others who work, study and live around them.

LinkedIn:
  Name: LinkedIn
  Description: LinkedIn is a social media platform that connects people with friends and others who work, study and live around them.